// Generated by Wrangler on Fri Sep 06 2024 16:37:36 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	MY_KV_NAMESPACE: KVNamespace;
}
