// Generated by Wrangler on Fri Sep 27 2024 16:55:08 GMT+0800 (中国标准时间)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	MY_KV1: KVNamespace;
	MY_DB1: D1Database;
}
