import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'

export const metadata = {
  title: 'ssr',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>root html</h1>
        {children}
      </body>
    </html>
  )
}